node {
	stage 'Checkout'
		checkout scm

	stage 'Build'
		bat 'nuget restore SolutionName.sln'
		bat """
			setlocal enabledelayedexpansion
			\"${tool 'MSBuild'}\" SolutionName.sln /p:Configuration=Release /p:Platform=\"Any CPU\" /p:ProductVersion=1.0.0.!BUILD_NUMBER!
			endlocal
		"""
	stage 'Archive'
		archive 'ProjectName/bin/Release/**'

}